name: Release Package
on:
  push:
    tags:
      - '*'

jobs:
  Test:
    runs-on: ubuntu-latest # Firefox in it
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@octocat'
      - run: npm install
      - run: DEBUG=eslint:cli-engine npm run lint:all
      - run: npm run build
      - run: npm run test:browser
      - run: npm run test:coverage
  Release:
    needs: Test
    runs-on: ubuntu-latest # Firefox in it
    strategy:
      matrix:
        node-version: [16.x]
    permissions:
      contents: write # for release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@octocat'
      - run: npm install
      - run: npm run build
      - run: npm ci
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sdk/dist/ringcentral.js
            sdk/dist/ringcentral.js.map
            sdk/dist/ringcentral.min.js
            sdk/dist/ringcentral.min.js.map
            subscriptions/dist/ringcentral-subscriptions.js
            subscriptions/dist/ringcentral-subscriptions.js.map
            subscriptions/dist/ringcentral-subscriptions.min.js
            subscriptions/dist/ringcentral-subscriptions.min.js.map
            subscriptions-deprecated/dist/ringcentral-subscriptions-deprecated.js
            subscriptions-deprecated/dist/ringcentral-subscriptions-deprecated.js.map
            subscriptions-deprecated/dist/ringcentral-subscriptions-deprecated.min.js
            subscriptions-deprecated/dist/ringcentral-subscriptions-deprecated.min.js.map
        env:
          GITHUB_REPOSITORY: SushilMallRC/ringcentral-js
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
